### ISSUE TITLE
Chime when counter reaches zero

### ISSUE THREAD

**Issue by cbruguera** [MatNascimento/StudyTimer#1]
Hi, this is a nice app, and surprisingly the **only** pomodoro app I've found that displays the timer on the icon in real time. Now, it seems there's no sound played after each period, isn't it possible to add this feature? Or am I missing some hidden setting somewhere? I think a sound alert would be great, and perhaps the only thing missing.

**Comment by MatNascimento** [comment]
Thank you for your feedback, the timer isn't done yet, recently I've been doing some refactoring on the code because I'm planning some new features to the extension. When I was developing the first version I even thought about doing a sound alert but I didn't find a good sound effect at first and just dropped the idea meanwhile, but since you and probably other people are missing this features I will try to implement it in the next version coming.

**Comment by MatNascimento** [comment]
The next version will also come with settings to customize the number of pomodoros and how much time each "stage" lasts, and support for other browsers.
Again, thank you for supporting my timer :)

**Comment by cbruguera** [comment]
Hey, I hadn't checked on this thread. Thanks for your reply.

In my opinion, your app is looking good. I would suggest to keep it as simple as possible, but doing each of the basic features the best way possible. The "pomodoro market" is filled to the brim with applications that you can ultra-customize and integrate with trello+asana+jira and github and even store proof of your pomodoros on the blockchain (that one just kidding), yet something as _basic_ as displaying a real-time counter on the tray or toolbar is missing! Go figure...

Personally, the value I see in the Pomodoro technique is that it teaches you to become aware of your activity in the _now_, whether it is that _now_ you are working or _now_ you're taking a break, it teaches you to achieve the most out of those (usually brief) periods; with practice one might be surprised of how much can be achieved in 25 minutes. However, as for mid-or-long term planning (or even for planning at all. e.g. multiple pomodoros in advance) I don't see that as too valuable to the Pomodoro technique; not that it's not compatible with Pomodoro, just not fundamental... Now, a **sound alert** when periods end is a _must_ (IMO). For example, I like to use my breaks to do quick yoga stretches, I'm not looking at my desktop at the time (it's a break after all, right?)

Just my two cents. :)

**Comment by MatNascimento** [comment]
Hi, it took some time but I finally manage to put a settings page on the extension and the **sound alert** is there too.
The Mozilla Add-ons Store is already up with the new version if you want to use it.

**Comment by cbruguera** [comment]
Hey this is great! I'll give it a check as soon as possible. Thanks for your work and the notice. 👍

**Comment by MatNascimento** [comment]
You're welcome
