### ISSUE TITLE
Custom sound alert volume

### ISSUE THREAD

**Issue by MatNascimento** [MatNascimento/StudyTimer#5]
Add option to choose the volume of the sound alert in the settings screen

**Comment by daedroza** [comment]
Hi, I also wanted a suggestion here. The notification sound is too low and very quick. Can we have a option for notification sound to ring for 2-5-7-10 seconds as option as well?

I really appreciate the plugin, thanks for all the work!

**Comment by MatNascimento** [comment]
Original issue fixed by commit [#7fb27bc](https://github.com/MatNascimento/StudyTimer/commit/7fb27bc089a63121466e0c43e87b7bd4d6904d17)

**Comment by MatNascimento** [comment]
@daedroza, great that you find it useful, you're welcome.
About your suggestion, it's not possible to make the audio longer with the library the extension is using.
I think a feature where the users could upload their own notification sound will probably help.
